name: Node CI

on: [push, pull_request]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - name: Run linter
        run: npm run lint:fix
      - name: Add and commit fixes
        uses: EndBug/add-and-commit@v4.2.0
        with:
          message: 'ci: fix linter issues'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
